[package]
name = "bluesky-firehose-stream"
version = "0.1.0"
edition = "2021"

[dependencies]
atrium-api = "0.24.8"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12" }
anyhow = "*"
atrium-xrpc-client = "0.5.10"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2.2.2"
async-tungstenite = { version = "0.28.0", features = [
    "tokio-rustls-webpki-roots",
    "tokio-runtime",
    "async-tls",
] }
futures = "0.3"
rustls = { version = "0.23.19", features = ["ring"] }
dotenvy = "0.15"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
atty = "0.2"
log = "0.4"
lingua = "1.6.2"
clap = { version = "4", features = ["derive", "env"] }
skystreamer = "0.2"
chrono = "0.4"
serde_ipld_dagcbor = "0.6"
rs-car-sync = "0.4"
cid = "0.11"
thiserror = "1"
